

/*Main menu*/
// Generated by CoffeeScript 1.9.2

/**
 @license Sticky-kit v1.1.2 | WTFPL | Leaf Corcoran 2015 | http://leafo.net
 */



$('.prices_block').mouseover(function (event) {
  if (window.innerWidth > 768) {
    if (!$(this).hasClass('active')) {
      $(this).addClass('active')
    }
  }
});

$('.prices_block').mouseout(function (event) {
  if (window.innerWidth > 768) {
    if ($(this).hasClass('active')) {
      $(this).removeClass('active')
    }
  }
});

$(window).click(function () {
  if ($('.prices_block').hasClass('active')) {
    $('.prices_block').removeClass('active');
  }
});

$('.prices_block').click(function (event) {
  event.stopPropagation();
  if ($(this).hasClass('active')) {
    $(this).removeClass('active');
  } else {
    $(this).addClass('active')
  }
});

(function () {
  var $, win;

  $ = this.jQuery || window.jQuery;

  win = $(window);

  $.fn.stick_in_parent = function (opts) {
    var doc, elm, enable_bottoming, fn, i, inner_scrolling, len, manual_spacer, offset_top, parent_selector,
      recalc_every, sticky_class;
    if (opts == null) {
      opts = {};
    }
    sticky_class = opts.sticky_class, inner_scrolling = opts.inner_scrolling, recalc_every = opts.recalc_every, parent_selector = opts.parent, offset_top = opts.offset_top, manual_spacer = opts.spacer, enable_bottoming = opts.bottoming;
    if (offset_top == null) {
      offset_top = 0;
    }
    if (parent_selector == null) {
      parent_selector = void 0;
    }
    if (inner_scrolling == null) {
      inner_scrolling = true;
    }
    if (sticky_class == null) {
      sticky_class = "is_stuck";
    }
    doc = $(document);
    if (enable_bottoming == null) {
      enable_bottoming = true;
    }
    fn = function (elm, padding_bottom, parent_top, parent_height, top, height, el_float, detached) {
      var bottomed, detach, fixed, last_pos, last_scroll_height, offset, parent, recalc, recalc_and_tick,
        recalc_counter, spacer, tick;
      if (elm.data("sticky_kit")) {
        return;
      }
      elm.data("sticky_kit", true);
      last_scroll_height = doc.height();
      parent = elm.parent();
      if (parent_selector != null) {
        parent = parent.closest(parent_selector);
      }
      if (!parent.length) {
        throw "failed to find stick parent";
      }
      fixed = false;
      bottomed = false;
      spacer = manual_spacer != null ? manual_spacer && elm.closest(manual_spacer) : $("<div />");
      if (spacer) {
        spacer.css('position', elm.css('position'));
      }
      recalc = function () {
        var border_top, padding_top, restore;
        if (detached) {
          return;
        }
        last_scroll_height = doc.height();
        border_top = parseInt(parent.css("border-top-width"), 10);
        padding_top = parseInt(parent.css("padding-top"), 10);
        padding_bottom = parseInt(parent.css("padding-bottom"), 10);
        parent_top = parent.offset().top + border_top + padding_top;
        parent_height = parent.height();
        if (fixed) {
          fixed = false;
          bottomed = false;
          if (manual_spacer == null) {
            elm.insertAfter(spacer);
            spacer.detach();
          }
          elm.css({
            position: "",
            top: "",
            width: "",
            bottom: ""
          }).removeClass(sticky_class);
          restore = true;
        }
        top = elm.offset().top - (parseInt(elm.css("margin-top"), 10) || 0) - offset_top;
        height = elm.outerHeight(true);
        el_float = elm.css("float");
        if (spacer) {
          spacer.css({
            width: elm.outerWidth(true),
            height: height,
            display: elm.css("display"),
            "vertical-align": elm.css("vertical-align"),
            "float": el_float
          });
        }
        if (restore) {
          return tick();
        }
      };
      recalc();
      if (height === parent_height) {
        return;
      }
      last_pos = void 0;
      offset = offset_top;
      recalc_counter = recalc_every;
      tick = function () {
        var css, delta, recalced, scroll, will_bottom, win_height;
        if (detached) {
          return;
        }
        recalced = false;
        if (recalc_counter != null) {
          recalc_counter -= 1;
          if (recalc_counter <= 0) {
            recalc_counter = recalc_every;
            recalc();
            recalced = true;
          }
        }
        if (!recalced && doc.height() !== last_scroll_height) {
          recalc();
          recalced = true;
        }
        scroll = win.scrollTop();
        if (last_pos != null) {
          delta = scroll - last_pos;
        }
        last_pos = scroll;
        if (fixed) {
          if (enable_bottoming) {
            will_bottom = scroll + height + offset > parent_height + parent_top;
            if (bottomed && !will_bottom) {
              bottomed = false;
              elm.css({
                position: "fixed",
                bottom: "",
                top: offset
              }).trigger("sticky_kit:unbottom");
            }
          }
          if (scroll < top) {
            fixed = false;
            offset = offset_top;
            if (manual_spacer == null) {
              if (el_float === "left" || el_float === "right") {
                elm.insertAfter(spacer);
              }
              spacer.detach();
            }
            css = {
              position: "",
              width: "",
              top: ""
            };
            elm.css(css).removeClass(sticky_class).trigger("sticky_kit:unstick");
          }
          if (inner_scrolling) {
            win_height = win.height();
            if (height + offset_top > win_height) {
              if (!bottomed) {
                offset -= delta;
                offset = Math.max(win_height - height, offset);
                offset = Math.min(offset_top, offset);
                if (fixed) {
                  elm.css({
                    top: offset + "px"
                  });
                }
              }
            }
          }
        } else {
          if (scroll > top) {
            fixed = true;
            css = {
              position: "fixed",
              top: offset
            };
            css.width = elm.css("box-sizing") === "border-box" ? elm.outerWidth() + "px" : elm.width() + "px";
            elm.css(css).addClass(sticky_class);
            if (manual_spacer == null) {
              elm.after(spacer);
              if (el_float === "left" || el_float === "right") {
                spacer.append(elm);
              }
            }
            elm.trigger("sticky_kit:stick");
          }
        }
        if (fixed && enable_bottoming) {
          if (will_bottom == null) {
            will_bottom = scroll + height + offset > parent_height + parent_top;
          }
          if (!bottomed && will_bottom) {
            bottomed = true;
            if (parent.css("position") === "static") {
              parent.css({
                position: "relative"
              });
            }
            return elm.css({
              position: "absolute",
              bottom: padding_bottom,
              top: "auto"
            }).trigger("sticky_kit:bottom");
          }
        }
      };
      recalc_and_tick = function () {
        recalc();
        return tick();
      };
      detach = function () {
        detached = true;
        win.off("touchmove", tick);
        win.off("scroll", tick);
        win.off("resize", recalc_and_tick);
        $(document.body).off("sticky_kit:recalc", recalc_and_tick);
        elm.off("sticky_kit:detach", detach);
        elm.removeData("sticky_kit");
        elm.css({
          position: "",
          bottom: "",
          top: "",
          width: ""
        });
        parent.position("position", "");
        if (fixed) {
          if (manual_spacer == null) {
            if (el_float === "left" || el_float === "right") {
              elm.insertAfter(spacer);
            }
            spacer.remove();
          }
          return elm.removeClass(sticky_class);
        }
      };
      win.on("touchmove", tick);
      win.on("scroll", tick);
      win.on("resize", recalc_and_tick);
      $(document.body).on("sticky_kit:recalc", recalc_and_tick);
      elm.on("sticky_kit:detach", detach);
      return setTimeout(tick, 0);
    };
    for (i = 0, len = this.length; i < len; i++) {
      elm = this[i];
      fn($(elm));
    }
    return this;
  };

}).call(this);


$(document).ready(function () {


  var isMobile = false; //initiate as false
  // device detection
  if (/(android|bb\d+|meego).+mobile|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(hone|od)|ipad|iris|kindle|Android|Silk|lge |maemo|midp|mmp|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|series(4|6)0|symbian|treo|up\.(browser|link)|vodafone|wap|windows (ce|phone)|xda|xiino/i.test(navigator.userAgent)
    || /1207|6310|6590|3gso|4thp|50[1-6]i|770s|802s|a wa|abac|ac(er|oo|s\-)|ai(ko|rn)|al(av|ca|co)|amoi|an(ex|ny|yw)|aptu|ar(ch|go)|as(te|us)|attw|au(di|\-m|r |s )|avan|be(ck|ll|nq)|bi(lb|rd)|bl(ac|az)|br(e|v)w|bumb|bw\-(n|u)|c55\/|capi|ccwa|cdm\-|cell|chtm|cldc|cmd\-|co(mp|nd)|craw|da(it|ll|ng)|dbte|dc\-s|devi|dica|dmob|do(c|p)o|ds(12|\-d)|el(49|ai)|em(l2|ul)|er(ic|k0)|esl8|ez([4-7]0|os|wa|ze)|fetc|fly(\-|_)|g1 u|g560|gene|gf\-5|g\-mo|go(\.w|od)|gr(ad|un)|haie|hcit|hd\-(m|p|t)|hei\-|hi(pt|ta)|hp( i|ip)|hs\-c|ht(c(\-| |_|a|g|p|s|t)|tp)|hu(aw|tc)|i\-(20|go|ma)|i230|iac( |\-|\/)|ibro|idea|ig01|ikom|im1k|inno|ipaq|iris|ja(t|v)a|jbro|jemu|jigs|kddi|keji|kgt( |\/)|klon|kpt |kwc\-|kyo(c|k)|le(no|xi)|lg( g|\/(k|l|u)|50|54|\-[a-w])|libw|lynx|m1\-w|m3ga|m50\/|ma(te|ui|xo)|mc(01|21|ca)|m\-cr|me(rc|ri)|mi(o8|oa|ts)|mmef|mo(01|02|bi|de|do|t(\-| |o|v)|zz)|mt(50|p1|v )|mwbp|mywa|n10[0-2]|n20[2-3]|n30(0|2)|n50(0|2|5)|n7(0(0|1)|10)|ne((c|m)\-|on|tf|wf|wg|wt)|nok(6|i)|nzph|o2im|op(ti|wv)|oran|owg1|p800|pan(a|d|t)|pdxg|pg(13|\-([1-8]|c))|phil|pire|pl(ay|uc)|pn\-2|po(ck|rt|se)|prox|psio|pt\-g|qa\-a|qc(07|12|21|32|60|\-[2-7]|i\-)|qtek|r380|r600|raks|rim9|ro(ve|zo)|s55\/|sa(ge|ma|mm|ms|ny|va)|sc(01|h\-|oo|p\-)|sdk\/|se(c(\-|0|1)|47|mc|nd|ri)|sgh\-|shar|sie(\-|m)|sk\-0|sl(45|id)|sm(al|ar|b3|it|t5)|so(ft|ny)|sp(01|h\-|v\-|v )|sy(01|mb)|t2(18|50)|t6(00|10|18)|ta(gt|lk)|tcl\-|tdg\-|tel(i|m)|tim\-|t\-mo|to(pl|sh)|ts(70|m\-|m3|m5)|tx\-9|up(\.b|g1|si)|utst|v400|v750|veri|vi(rg|te)|vk(40|5[0-3]|\-v)|vm40|voda|vulc|vx(52|53|60|61|70|80|81|83|85|98)|w3c(\-| )|webc|whit|wi(g |nc|nw)|wmlb|wonu|x700|yas\-|your|zeto|zte\-/i.test(navigator.userAgent.substr(0, 4))) isMobile = true;


  //SCROLL LOCK

  // left: 37, up: 38, right: 39, down: 40,
  // spacebar: 32, pageup: 33, pagedown: 34, end: 35, home: 36
  var keys = { 37: 1, 38: 1, 39: 1, 40: 1 };

  function preventDefault(e) {
    e = e || window.event;
    if (e.preventDefault)
      e.preventDefault();
    e.returnValue = false;
  }

  function preventDefaultForScrollKeys(e) {
    if (keys[e.keyCode]) {
      preventDefault(e);
      return false;
    }
  }

  function disableBodyScroll() {
    $('body').css('overflow', 'hidden');
  }

  function enableScroll() {
    if (window.removeEventListener)
      window.removeEventListener('DOMMouseScroll', preventDefault, false);
    window.onmousewheel = document.onmousewheel = null;
    window.onwheel = null;
    window.ontouchmove = null;
    document.onkeydown = null;
  }

  function enableBodyScroll() {
    $('body').css('overflow', 'auto');
  }


  /*Info-carousel */


  if ($(".portfolio-v2")) {
    $(".portfolio-v2").owlCarousel({
      lazyLoad: true,
      loop: true,
      nav: true,
      // autoWidth: true,
      navText: ['', ''],
      dots: false,
      center: false,
      responsive: {
        0: { items: 1 },
        1024: { items: 3 }
      }
    });
  }

  if ($(window).outerWidth() <= 767) {
    $('.pl_stages_title').on('click', function () {
      priceChevron = $(this).find('.price_chevron');
      if ($(this).next().is(':visible')) {
        $(this).next().hide();
        priceChevron.css({ 'transform': 'rotate(0deg' });
      } else {
        $(this).next().show();
        priceChevron.css({ 'transform': 'rotate(180deg' });
      }
    });

  }


  // if ( $(window).outerWidth() <=1000 ) {
  //     console.log('fffffdddddd')
  //     $('.obj-gallery-gal_thumbs_wrapper').removeClass('scroll-pane');
  // }
  console.log($(window).outerWidth());
  if ($(window).outerWidth() <= 768) {

    // $('.obj-gallery-gal_thumbs_wrapper').removeClass('scroll-pane');
    // $('.obj-gallery-wr_galls').outerHeight( $('.obj-gallery-wr_container:eq(0)').outerHeight() + 20 );
    //
    // $(window).resize(function(){
    //     $('.obj-gallery-wr_galls').outerHeight( $('.obj-gallery-wr_container:eq(0)').outerHeight() + 40 );
    // });

    $('.obj-gallery-gal_thumbs .th_item').each(function (index) {
      // console.log(index);
      if (index == 0) {
        $(this).addClass('obj-gallery-th-item-active');
      }
    });

    $('.obj-gallery-gal_thumbs .th_item').on('click', function () {
      $('.obj-gallery-gal_thumbs .th_item').removeClass('obj-gallery-th-item-active');
      $(this).addClass('obj-gallery-th-item-active');
    });

  }

  $(".quality-carousel").owlCarousel({
    lazyLoad: true,
    items: 3,
    loop: false,
    nav: true,
    autoWidth: true,
    navText: ['', ''],
    margin: 0,
    dots: false,
    margin: 1,
    center: true
  });


  $(".js-carousel").owlCarousel({
    lazyLoad: true,
    items: 2,
    loop: false,
    nav: false,
    autoWidth: true,
    margin: 0,
    dots: false,

  });

  /*Gallery-carousel */

  $('.nana').owlCarousel({
    lazyLoad: true,
    loop: false,
    items: 1,
    thumbs: true,
    thumbImage: true,
    thumbContainerClass: 'owl-thumbs-gall',
    thumbItemClass: 'owl-thumb-item-gall',
    dots: false,
    nav: true,
    navText: ['', ''],
    responsive: {
      0: { nav: true },
      768: { nav: false }
    }
  });

  $('.js-gallery-inner').owlCarousel({
    lazyLoad: true,
    loop: false,
    items: 1,
    thumbs: true,
    thumbImage: true,
    thumbContainerClass: 'owl-thumbs-gall',
    thumbItemClass: 'owl-thumb-item-gall',
    dots: false,
    nav: true,
    navText: ['', ''],
    responsive: {
      0: { nav: true },
      768: { nav: false }
    }
  });

  $('.js-gallery-inner_i').owlCarousel({
    lazyLoad: true,
    loop: false,
    items: 1,
    thumbs: false,
    thumbImage: false,
    dots: true,
    nav: true,
    navText: ['', ''],
    responsive: {
      0: { nav: true },
      768: { nav: true }
    },
    onTranslated: function (event) {
      var items = event.item.count;
      var item = event.item.index;

      if (item == 0) {
        $(event.target).attr('data-start', 1)
      } else {
        $(event.target).attr('data-start', 0)
      }

      if (item + 1 == items) {
        $(event.target).attr('data-end', 1)
      } else {
        $(event.target).attr('data-end', 0)
      }

    }
  });

  $('.js-gallery-inner_i .owl-next').click(function () {
    var th_car = $(this).parents('.js-gallery-inner_i');


    var th_active = th_car.find('.owl-item.active').index();
    var th_total = th_car.find('.owl-item').length;

    if (th_car.attr('data-end') == 1) {
      var step_car = th_car.parents('.js-step');

      step_car.trigger('next.owl.carousel', [0]);
    }

    var th_car_parent = th_car.parents('.gallery-wr');
    var th_car_index = th_car.parents('.gallery-wr').find('.owl-thumb-item.active').index();
    th_car_parent.find('.gal_select_list_item').removeClass('active');
    th_car_parent.find('.gal_select_list_item:eq(' + th_car_index + ')').addClass('active');


  });


  $('.js-gallery-inner_i .owl-prev').click(function () {
    var th_car = $(this).parents('.js-gallery-inner_i');

    var th_active = th_car.find('.owl-item.active').index();
    var th_total = th_car.find('.owl-item').length;

    if (th_car.attr('data-start') == 1) {
      var step_car = th_car.parents('.js-step');

      step_car.trigger('prev.owl.carousel', [0]);

    }
    var th_car_parent = th_car.parents('.gallery-wr');
    var th_car_index = th_car.parents('.gallery-wr').find('.owl-thumb-item.active').index();
    th_car_parent.find('.gal_select_list_item').removeClass('active');
    th_car_parent.find('.gal_select_list_item:eq(' + th_car_index + ')').addClass('active');


  });


  $('.js-gallery-inner_ii').owlCarousel({
    lazyLoad: true,
    loop: false,
    items: 1,
    thumbs: false,
    thumbImage: false,
    dots: true,
    nav: true,
    navText: ['', ''],
    responsive: {
      0: { nav: true },
      768: { nav: true }
    },
    onTranslated: function (event) {
      var items = event.item.count;
      var item = event.item.index;

      if (item == 0) {
        $(event.target).attr('data-start', 1)
      } else {
        $(event.target).attr('data-start', 0)
      }

      if (item + 1 == items) {
        $(event.target).attr('data-end', 1)
      } else {
        $(event.target).attr('data-end', 0)
      }

    }
  });


  $('.js-obj-gallery').owlCarousel({
    lazyLoad: true,
    nav: false,
    navText: "",
    loop: true,
    items: 1,
    mouseDrag: false,
    touchDrag: false,
    dots: false,
    onTranslated: function (event) {
      var items = event.item.count;
      var item = event.item.index;

      if (item == 0) {
        $(event.target).attr('data-start', 1)
      } else {
        $(event.target).attr('data-start', 0)
      }

      if (item + 1 == items) {
        $(event.target).attr('data-end', 1)
      } else {
        $(event.target).attr('data-end', 0)
      }

    }
  });

  /*Scrollbar gallery*/
  jQuery('.owl-thumbs-gall').scrollbar({
    autoScrollSize: false
  });

  $('.hamburger-menu').on('click', function () {
    $('.bar').toggleClass('animate');
    $('.menu-mobile').toggleClass('open');
  })


  $('.masonry-cont-mobile').owlCarousel({
    lazyLoad: true,
    navigation: true,
    slideSpeed: 300,
    paginationSpeed: 400,
    smartSpeed: 900,
    navigationText: ["", ""],
    stopOnHover: true,
    pagination: false,
    items: 1,
    dots: true,
    nav: true,
    navText: ["", ""],
    slideBy: 1,
    touchDrag: false,
    onTranslated: function (event) {
      var items = event.item.count;
      var item = event.item.index;

      if (item == 0) {
        $(event.target).attr('data-start', 1)
      } else {
        $(event.target).attr('data-start', 0)
      }

      if (item + 1 == items) {
        $(event.target).attr('data-end', 1)
      } else {
        $(event.target).attr('data-end', 0)
      }

    }
  });


  $('.owl-step-carousel').owlCarousel({
    lazyLoad: true,
    navigation: true,
    slideSpeed: 300,
    paginationSpeed: 400,
    smartSpeed: 900,
    navigationText: ["", ""],
    stopOnHover: true,
    pagination: false,
    items: 1,
    dots: false,
    nav: true,
    navText: ["", ""],
    slideBy: 1,
    onTranslated: function (event) {
      var items = event.item.count;
      var item = event.item.index;

      if (item == 0) {
        $(event.target).attr('data-start', 1)
      } else {
        $(event.target).attr('data-start', 0)
      }

      if (item + 1 == items) {
        $(event.target).attr('data-end', 1)
      } else {
        $(event.target).attr('data-end', 0)
      }

    }
  });

  //    if( window.outerWidth <= 767 ) {
  //        $('.brig-masonry').addClass('owl-carousel').owlCarousel({lazyLoad: true,
  //            navigation: true,
  //            slideSpeed: 300,
  //            paginationSpeed: 400,
  //            smartSpeed: 900,
  //            navigationText: ["", ""],
  //            stopOnHover: true,
  //            pagination: false,
  //            items: 1,
  //            dots: false,
  //            nav: true,
  //            navText: ["", ""],
  //            slideBy: 1,
  //        });
  //
  //    }


  $('.js-step').owlCarousel({
    lazyLoad: true,
    loop: false,
    items: 1,
    mouseDrag: false,
    touchDrag: false,
    //animateOut: 'none',
    // animateIn: 'none',
    thumbs: true,
    thumbImage: false,
    thumbsPrerendered: true,
    dots: false
  });


  $('.obj-gallery-gal_stage').owlCarousel({
    lazyLoad: true,
    loop: false,
    items: 1,
    thumbs: true,
    margin: 1,
    thumbImage: false,
    thumbsPrerendered: true,
    dots: false,
    nav: true,
    navText: ['', ''],
    onTranslated: function (event) {
      var items = event.item.count;
      var item = event.item.index;

      if (item == 0) {
        $(event.target).attr('data-start', 1)
      } else {
        $(event.target).attr('data-start', 0)
      }

      if (item + 1 == items) {
        $(event.target).attr('data-end', 1)
      } else {
        $(event.target).attr('data-end', 0)
      }

    }
    //onChanged : function (event) {
    //    var current = event.item.index;
    //    console.log(current);
    //
    //    $('.obj-gallery-gal_thumbs_wrapper .th_item').removeClass('active');
    //    $('.obj-gallery-gal_thumbs_wrapper .th_item:eq('+current+')').addClass('active');
    //}
  });

  $('.th_item').click(function () {
    var th_index = $(this).index();
    // console.log(th_index);

    $('.obj-gallery-wr_container').removeClass('active');
    $('.obj-gallery-wr_container:eq(' + th_index + ')').addClass('active');


    $('.th_item').removeClass('active');
    $(this).addClass('active');


    //$('.obj-gallery-gal_stage').trigger('to.owl.carousel', [th_index,300]);
  });


  /*Modal*/

  $(".js-modal").fancybox({
    arrows: false,
    toolbar: false,
    infobar: false,
    animationEffect: "fade",
    modal: false,
    'width': 940,
    //  parentEl : '.feedback_wrapper',
    clickContent: function (current, event) {
      return current.type === 'image' ? false : false;
    },
  });

  $(".various").fancybox({
    toolbar: false,
    maxWidth: 500,
  });


  $('.js-phone').inputmask({ "mask": "+7 (999) 999-9999" });


  $('.brig-masonry-col-2').outerHeight($('.brig-masonry-col').outerHeight());
  setTimeout(function () {
    $('.brig-masonry-col-2').outerHeight($('.brig-masonry-col').outerHeight());
  }, 300)

  $(window).resize(function () {
    $('.brig-masonry-col-2').outerHeight($('.brig-masonry-col').outerHeight());

  });


  if (typeof $.fn.jScrollPane !== 'undefined') {
    $('.scroll-pane').jScrollPane({
      showArrows: false
    });
  }


  $("[data-fancybox]").fancybox({
    arrows: true,
    toolbar: true,
    infobar: true,
    animationEffect: "fade",
    modal: false,
    'width': 940,
    //  parentEl : '.feedback_wrapper',
    clickContent: function (current, event) {
      return current.type === 'image' ? false : false;
    },
    tpl: {
      closeBtn: '<div title="Close" class="fancybox-item fancybox-close">[my closing html]</div>'
    },
    baseTpl:
      '<div class="fancybox-container" role="dialog" tabindex="-1">' +
      '<div class="fancybox-bg"></div>' +
      '<div class="fancybox-inner">' +
      '<div class="fancybox-toolbar">' +
      '<div class="close_button"><button data-fancybox-close class="fancybox-button fancybox-button--close" title="{{CLOSE}}"></button></div>' +
      '</div>' +
      '<div class="fancybox-navigation">' +
      '<button data-fancybox-prev title="{{PREV}}" class="fancybox-arrow fancybox-arrow--left" />' +
      '<button data-fancybox-next title="{{NEXT}}" class="fancybox-arrow fancybox-arrow--right" />' +
      '</div>' +
      '<div class="fancybox-stage"></div>' +
      '<div class="fancybox-caption-wrap">' +
      '<div class="fancybox-caption"></div>' +
      '</div>' +
      '</div>' +
      '</div>',


    btnTpl: {
      slideShow: '<button data-fancybox-play class="fancybox-button fancybox-button--play" title="{{PLAY_START}}"></button>',
      fullScreen: '<button data-fancybox-fullscreen class="fancybox-button fancybox-button--fullscreen" title="{{FULL_SCREEN}}"></button>',
      thumbs: '',
      close: '<button data-fancybox-close class="fancybox-button fancybox-button--close" title="{{CLOSE}}"></button>',

      // This small close button will be appended to your html/inline/ajax content by default,
      // if "smallBtn" option is not set to false
      smallBtn: '<button data-fancybox-close class="fancybox-close-small" title="{{CLOSE}}"></button>'
    },

  });


  // $("[data-instagram]").fancybox({
  //     arrows : true,
  //     toolbar : true,
  //     infobar : true,
  //     animationEffect: "fade",
  //     modal: false,
  //     'width'         : 940,
  //     //  parentEl : '.feedback_wrapper',
  //     clickContent : function( current, event ) {
  //         return current.type === 'image' ? false : false;
  //     },
  //     tpl: {
  //         closeBtn: '<div title="Close" class="fancybox-item fancybox-close">[my closing html]</div>'
  //     },
  //     baseTpl	:
  //     '<div class="fancybox-container" role="dialog" tabindex="-1">' +
  //     '<div class="fancybox-bg"></div>' +
  //     '<div class="fancybox-inner">' +
  //     '<div class="fancybox-toolbar">' +
  //     '<div class="close_button"><button data-fancybox-close class="fancybox-button fancybox-button--close" title="{{CLOSE}}"></button></div>' +
  //     '</div>' +
  //     '<div class="fancybox-navigation">' +
  //     '<button data-fancybox-prev title="{{PREV}}" class="fancybox-arrow fancybox-arrow--left" />' +
  //     '<button data-fancybox-next title="{{NEXT}}" class="fancybox-arrow fancybox-arrow--right" />' +
  //     '</div>' +
  //     '<div class="fancybox-stage"></div>' +
  //     '<div class="fancybox-caption-wrap">' +
  //     '<div class="fancybox-caption"></div>' +
  //     '</div>' +
  //     '</div>' +
  //     '</div>',
  //
  //     btnTpl : {
  //         slideShow  : '<button data-fancybox-play class="fancybox-button fancybox-button--play" title="{{PLAY_START}}"></button>',
  //         fullScreen : '<button data-fancybox-fullscreen class="fancybox-button fancybox-button--fullscreen" title="{{FULL_SCREEN}}"></button>',
  //         thumbs     : '',
  //         close      : '<button data-fancybox-close class="fancybox-button fancybox-button--close" title="{{CLOSE}}"></button>',
  //
  //         // This small close button will be appended to your html/inline/ajax content by default,
  //         // if "smallBtn" option is not set to false
  //         smallBtn   : '<button data-fancybox-close class="fancybox-close-small" title="{{CLOSE}}"></button>'
  //     },
  //
  // });


  //REQUEST PP

  $('.pp_req_close, .pp_close').click(function () {
    $('.pp').removeClass('show');
    enableBodyScroll();
    enableScroll();
  });

  $(document).keyup(function (e) {
    if (e.keyCode == 27) { // escape key maps to keycode `27`
      $('.pp').removeClass('show');
      enableBodyScroll();
      enableScroll();
    }
  });


  (function () {
    $('.frame-c').each(function () {
      var $frame = $(this);
      var $slidee = $frame.children('ul').eq(0);
      var $wrap = $frame.parent();

      // Call Sly on frame
      $frame.sly({
        horizontal: 1,
        itemNav: 'basic',
        activateMiddle: false,
        smart: 1,
        // activateOn: 'click',
        mouseDragging: 1,
        touchDragging: 1,
        releaseSwing: 1,
        startAt: 0,
        scrollBar: $wrap.find('.scrollbar'),
        scrollBy: 0,
        //  pagesBar: $wrap.find('.pages'),
        //  activatePageOn: 'click',
        speed: 400,
        moveBy: 600,
        elasticBounds: 1,
        dragHandle: 1,
        dynamicHandle: 1,
        clickBar: 1,
        //nextPage: $slidee,
        pagesBar: $frame.children('.page-bar').eq(0),
        pageBuilder:          // Page item generator.
          function (index) {
            return '<span></span>';
          },

      });

      $frame.find('.info-carousel-prev').click(function (e) {
        e.stopPropagation();
        e.preventDefault();
        console.log('prev', $frame);
        $frame.sly('prevPage');
      })


      $(window).resize(function () {
        $frame.sly('reload')
      });
    });
    //$slidee.sly('on','click',function(e,i){
    //    console.log('1234');
    //    $frame.slideTo($frame.items[6].center);
    //});



  }());


  $('.info-carousel').click(function () {
    var gal = $(this);
    var gal_width = gal.find('ul').outerWidth();
    var win_width = $(window).outerWidth();

    var gal_i_width = gal.find('.item:eq(0)').outerWidth();
    var currTrans = gal.find('ul.clearfix').css('-webkit-transform').split(/[()]/)[1];
    var posx = currTrans.split(',')[4];


    if (gal_width <= posx * -1 + win_width) {
      console.log(gal_width);
      console.log('1');
      gal.sly('slideTo', 0, false);

    } else {
      console.log('2');
      gal.sly('slideTo', posx * -1 + gal_i_width + 1, false);
    }


  });

  (function () {
    var $frame = $('#basic2');
    var $slidee = $frame.children('ul').eq(0);
    var $wrap = $frame.parent();

    // Call Sly on frame
    $frame.sly({
      horizontal: 1,
      itemNav: 'basic',
      smart: true,
      activateMiddle: false,
      smart: 1,
      // activateOn: 'click',
      mouseDragging: 1,
      touchDragging: 1,
      releaseSwing: 1,
      startAt: 0,
      scrollBar: $wrap.find('.scrollbar'),
      scrollBy: 0,
      //  pagesBar: $wrap.find('.pages'),
      //  activatePageOn: 'click',
      speed: 400,
      moveBy: 600,
      elasticBounds: 1,
      dragHandle: 1,
      dynamicHandle: 1,
      clickBar: 1,
      nextPage: $slidee


    });

    $(window).resize(function () {
      $frame.sly('reload')
    });


  }());


  //Mobile steps

  // $('.gal_select_value_box').click(function(){
  //
  //     var th_p =  $(this).parent();
  //     var th_list = $(this).parent().find('.gal_select_list');
  //
  //     th_list.slideToggle(200);
  //     $(this).toggleClass('active');
  // //});

  $('.gal_select_list_item').click(function () {

    var th_index = $(this).index();
    var th_text = $(this).text();
    console.log(th_index);

    var th_slider = $(this).parent().attr('data-slider-id');

    $(this).parent().find('.gal_select_list_item').removeClass('active');
    $(this).addClass('active');

    var th_list = $(this).parent().parent().parent().find('.gal_select_list');
    $(this).parent().parent().parent().find('.gal_select_value').text(th_text);

    // th_list.slideToggle(200);

    $('.js-step[data-slider-id=' + th_slider + ']').trigger("to.owl.carousel", [th_index, 1, true]);


  });


  //Video Gallary

  $('.js-fancy_video').click(function (event) {
    var th = $(this);
    var th_but = $(this).parent().parent();

    var th_p = $(this).parent().parent().parent();
    var th_href = $(this).attr('data-videourl');

    th_but.hide();

    var if_width = th_p.width();
    var if_height = th_p.height();

    th_p.find('img').fadeOut(500);
    th_p.find('.video-block-wrap-caption').fadeOut(500);
    th_p.addClass('active');
    th_p.height(if_height).width(if_width);
    th_p.append('<iframe src="' + th_href + '?autoplay=1&color=ffffff&title=0&portrait=0" autoplay="true" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen style="width: ' + if_width + 'px;height:' + if_height + 'px;border:none"></iframe>');
  });


  $(window).trigger('resize');
  $(window).resize(function () {
    if (typeof $.fn.jScrollPane !== 'undefined') {
      $('.scroll-pane').jScrollPane({
        showArrows: false
      });
    }

  });


  //Article simple gallary


  $('.article_simple_gal').owlCarousel({
    lazyLoad: true,
    loop: false,
    items: 1,
    thumbs: true,
    margin: 1,
    thumbImage: false,
    thumbsPrerendered: false,
    dots: true,
    nav: true,
    navText: ['', ''],
    onTranslated: function (event) {
      var items = event.item.count;
      var item = event.item.index;

      if (item == 0) {
        $(event.target).attr('data-start', 1)
      } else {
        $(event.target).attr('data-start', 0)
      }

      if (item + 1 == items) {
        $(event.target).attr('data-end', 1)
      } else {
        $(event.target).attr('data-end', 0)
      }

    }

  });

  //Scroll by click
  //  $('.art_block_img').click(function(){
  //      var th_car = $(this).parents('.owl-carousel');
  //
  //      th_car.trigger('next.owl.carousel', [300]);
  //
  // // });


  $('.cgb_left_gallary').owlCarousel({
    lazyLoad: true,
    loop: false,
    items: 1,
    margin: 1,
    dots: true,
    nav: true,
    navText: ['', ''],
    onTranslated: function (event) {
      var items = event.item.count;
      var item = event.item.index;

      if (item == 0) {
        $(event.target).attr('data-start', 1)
      } else {
        $(event.target).attr('data-start', 0)
      }

      if (item + 1 == items) {
        $(event.target).attr('data-end', 1)
      } else {
        $(event.target).attr('data-end', 0)
      }

    }

    // onChanged : function (event) {
    //     var current = event.item.index;
    //     var element   = event.target;
    //     console.log(element);
    //     // element.parents('.coplex_gallary_box').find('.cgb_left_gallary_thumbs_item').removeClass('active');
    //     // element.parents('.coplex_gallary_box').find('.cgb_left_gallary_thumbs_item:eq('+current+')').addClass('active');
    //
    // }

  });


  $('.cgb_left_gallary').each(function () {


    var $this_ = $(this);


    $this_.on('changed.owl.carousel', function (event) {
      var current = event.item.index;
      var element = event.target;
      console.log(element);
      $this_.parents('.coplex_gallary_box').find('.cgb_left_gallary_thumbs_item').removeClass('active');
      $this_.parents('.coplex_gallary_box').find('.cgb_left_gallary_thumbs_item:eq(' + current + ')').addClass('active');

    });


  });


  //coplex_gallary_box

  $('.coplex_gallary_box').each(function () {
    var l_side = $(this).find('.cgb_left');
    var r_side = $(this).find('.cgb_right');

    var r_side_height = r_side.outerHeight();

    var l_side_height = l_side.outerHeight();

    r_side.find('.cgb_left_gallary_thumbs').outerHeight(l_side_height);


    if (r_side_height > l_side_height) {
      r_side.find('.cgb_left_gallary_thumbs').jScrollPane({
        showArrows: false
      });
    }

  });


  $('.cgb_left_gallary_thumbs_item ').click(function () {
    var th_idx = $(this).index();
    console.log(th_idx)

    $(this).parent().find('.cgb_left_gallary_thumbs_item').removeClass('active');
    $(this).addClass('active');


    var th_owl = $(this).parents('.coplex_gallary_box').find('.cgb_left_gallary');

    th_owl.trigger("to.owl.carousel", [th_idx, 300, true]);


  });


  //SCROLLS
  $("a.scrollto").click(function () {
    var elementClick = $(this).attr("href");
    var destination = $(elementClick).offset().top;
    jQuery("html:not(:animated),body:not(:animated)").animate({ scrollTop: destination - 100 }, 800);
    return false;
  });
  //SCROLLS END

  //Scroll by click
  // $('.portfolio-gallery-inner-item').click(function(){
  //     var th_car = $(this).parents('.owl-carousel');
  //
  //     th_car.trigger('next.owl.carousel', [300]);
  //
  // });
  //
  // $('.video-block-item').click(function(){
  //     var th_car = $(this).parents('.owl-carousel');
  //
  //     th_car.trigger('next.owl.carousel', [300]);
  //
  // });
  //
  //
  // $('.article_simple_gal_item').click(function(){
  //     var th_car = $(this).parents('.owl-carousel');
  //
  //     th_car.trigger('next.owl.carousel', [300]);
  //
  // });
  //
  //
  //
  // //Scroll by click
  // $('.gallery-inner-item').click(function(){
  //    // var th_car = $(this).parents('.js-gallery-inner_i');
  //     var th_car3 = $(this).parents('.step-gallery-item');
  //
  //    // th_car3.trigger('next.owl.carousel', [300]);
  //
  // });
  //
  // $('.pp_supergal_item').click(function(){
  //     var th_car = $(this).parents('.owl-carousel');
  //
  //     th_car.trigger('next.owl.carousel', [300]);
  //
  // });


  //PP SuperGal


  setTimeout(function () {
    supergals_init();
  }, 300);


  $('.pp_supergal').owlCarousel({
    lazyLoad: true,
    loop: false,
    items: 1,
    thumbs: true,
    margin: 1,
    mouseDrag: false,
    touchDrag: true,
    // pullDrag: true,
    // freeDrag: true,
    thumbImage: false,
    thumbsPrerendered: true,
    dots: false,
    nav: true,
    navText: ['', ''],
    onChanged: function (event) {
      var current = event.item.index;
      var gal = $(event.target);

      gal.parents('.gallary_pp_block').find('.th_l_item').removeClass('active');
      gal.parents('.gallary_pp_block').find('.th_l_item:eq(' + current + ')').addClass('active');

    },
    onTranslated: function (event) {
      var items = event.item.count;
      var item = event.item.index;

      if (item == 0) {
        $(event.target).attr('data-start', 1)
      } else {
        $(event.target).attr('data-start', 0)
      }

      if (item + 1 == items) {
        $(event.target).attr('data-end', 1)
      } else {
        $(event.target).attr('data-end', 0)
      }

    }
  });

  $('.th_l_item').click(function () {
    var th_index = $(this).index();
    $(this).parents('.gallary_pp_block').find('.pp_supergal').trigger('to.owl.carousel', [th_index, 300]);
  });


  //16:9 blocks
  var coef = 0.6;

  $('.video-block-wrap').each(function () {
    var th_parent = $(this).attr('data-parent');

    var th_p1 = $(this).parents('.video-block-item_ii');
    var th_p2 = $(this).parents('.video-cont');
    var th_p3 = $(this).parents('.video-block-item');

    var bl_width = $('.' + th_parent).outerWidth();


    $(th_p1).height(bl_width * coef);
    $(th_p2).height(bl_width * coef);
    $(th_p3).height(bl_width * coef);


  });


  $(window).resize(function () {
    $('.video-block-wrap').each(function () {
      var th_parent = $(this).attr('data-parent');

      var th_p1 = $(this).parents('.video-block-item_ii');
      var th_p2 = $(this).parents('.video-cont');
      var th_p3 = $(this).parents('.video-block-item');

      var bl_width = $('.' + th_parent).outerWidth();


      $(th_p1).height(bl_width * coef);
      $(th_p2).height(bl_width * coef);
      $(th_p3).height(bl_width * coef);


    });

  });


  $('.mobmenubtn').on('click', function () {
    $('.bar').toggleClass('animate');
    $('.mobile_menu').toggleClass('open');

    if ($('.mobile_menu').hasClass('open')) {
      //  disableScroll();
      disableBodyScroll();
    } else {
      //  enableScroll();
      enableBodyScroll();
    }
  });


  //Mobile Menu

  if ($(window).outerWidth() < 767) {

    var menu_h = $('.mobile_menu_wrap').outerHeight();
    var win_h = $(window).outerHeight();


    if (menu_h > win_h - $('.l-main-block').outerHeight()) {
      $('.mobile_menu_wrap').outerHeight(win_h - $('.l-main-block').outerHeight());

      $('.mobile_menu_wrap').jScrollPane({
        showArrows: false
      });
    }
  }

  // function touchTest() {
  //     document.getElementsByClassName('gallary_pp_block').addEventListener('touchstart', function () { alert ('touch'); } , false);
  //     document.getElementsByClassName('gallary_pp_block').addEventListener('click', function () { alert('click'); } , false);
  // }
  //
  // document.addEventListener('DOMContentLoaded', touchTest);
  // var el = document.getElementsByClassName('gallary_pp_block');
  //
  //
  // function baba() {
  //     console.log('baba');
  // }
  // el.addEventListener('touchstart', baba, true);


  //Strange cycle
  $('.owl-next').click(function () {
    if (!$(this).parents('.step-gallery-item').length) {
      var th_car = $(this).parents('.owl-carousel');
      // console.log('touch click');

      if (th_car.attr('data-end') == '1') {
        th_car.trigger('to.owl.carousel', [0, 300]);
        th_car.attr('data-end', 0);
        return;
      }

      var th_active = th_car.find('.owl-item.active').index();
      var th_total = th_car.find('.owl-item').length;

      // console.log( th_active );
      // console.log( th_total );

      if (th_active + 1 == th_total) {

        th_car.attr('data-end', 1);

      } else {
        th_car.attr('data-end', 0);

      }

    }

  });


  //Process objects

  if ($(window).outerWidth() <= 1000) {

    // $('.obj-gallery-gal_thumbs_wrapper').removeClass('scroll-pane');

    // console.log('убирается скролл панель');


    // $('.obj-gallery-wr_galls').outerHeight( $('.obj-gallery-wr_container:eq(0)').outerHeight() + 40 );
    //
    // $(window).resize(function(){
    //     $('.obj-gallery-wr_galls').outerHeight( $('.obj-gallery-wr_container:eq(0)').outerHeight() + 40 );
    // });
  }


  //Mobile mosaic spoiler

  $('.mosaic_gals_spoiler_showme').click(function () {
    $(this).closest('.mosaic_gal_wrapper').find('.hidden-in-mob').removeClass('hidden-in-mob');
    $(this).remove();

  });


  //Calculator

  $('.calc_table_col1 span').click(function () {

    if (!$(this).hasClass('active')) {
      $('.calc_table_col1 span').removeClass('active');
      $(this).addClass('active');

      var th_p = $(this).parents('.calc_table_row');

      $('.calc_table_row_spoiler').slideUp(300);
      th_p.find('.calc_table_row_spoiler').slideDown(300);
    } else {
      $(this).removeClass('active');
      $('.calc_table_row_spoiler').slideUp(300);

    }
  });

  function calc_the_calc() {
    var price_m2_work = parseInt($('.ch_trigger.active').data('price_work'));
    var price_m2_mat = parseInt($('.ch_trigger.active').data('price_material'));

    if (!($('.calc_input').data('coef0') && $('.calc_input').data('coef1') && $('.calc_input').data('coef2'))) {
      return;
    }
    var square = parseInt($('.calc_input').val());
    var coef0 = $('.calc_input').data('coef0').split(';');
    var coef1 = $('.calc_input').data('coef1').toString().split(';');
    var coef2 = $('.calc_input').data('coef2').toString().split(';');
    var calc_coef = 1;
    if (square >= coef0[0] && square < coef0[1]) {
      calc_coef = coef0[2];
    }
    if (square >= coef1[0] && square < coef1[1]) {
      calc_coef = coef1[2];
    }
    if (square >= coef2[0] && square < coef2[1]) {
      calc_coef = coef2[2];
    }

    var total_work = price_m2_work * square * calc_coef;
    var total_mat = price_m2_mat * square * calc_coef;

    var work_cost = 0;
    var mats_cost = 0;

    console.log('total_work', total_work);
    console.log('total_mat', total_mat);

    $('.calc_table_col2:visible').each(function () {
      if (!$(this).hasClass('calc_table_col_head')) {
        var th_perc = parseFloat($(this).attr('data-perc'));

        var th_val = total_work * th_perc / 100;
        th_val = Math.round(th_val / 100) * 100;
        work_cost += th_val;

        if (th_val <= 0) {
          $(this).text('-');
        } else {
          th_val = th_val.toString().replace(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1 ");

          $(this).text(th_val + ' р');
          $('.w-' + $(this).data('id') + '-1').html(th_val + ' р');
        }
      }

    });

    $('.calc_table_col3:visible').each(function () {

      if (!$(this).hasClass('calc_table_col_head')) {
        var th_perc = parseFloat($(this).attr('data-perc'));
        var th_val = total_mat * th_perc / 100;

        mats_cost += th_val;
        th_val = th_val.toFixed();

        if (th_val <= 0) {
          $(this).text('-');
        } else {
          th_val = th_val.toString().replace(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1 ");
          $(this).text(th_val + ' р');
          $('.w-' + $(this).data('id') + '-2').html(th_val + ' р');
        }

      }

    });

    mats_cost = mats_cost.toFixed();


    if (work_cost <= 0) {
      $('.calc_f_val_work').text('-');
    } else {
      $('.calc_f_val_work').text(work_cost.toString().replace(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1 ") + ' р');
    }
    if (mats_cost <= 0) {
      $('.calc_f_val_mat').text('-');
    } else {
      $('.calc_f_val_mat').text(mats_cost.toString().replace(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1 ") + ' р');

    }


  }


  $('.ch_trigger').click(function () {
    $('.ch_trigger').removeClass('active');
    $(this).addClass('active');

    $('.repairs').hide();
    $('.repair_' + $(this).data('id')).show();

    $('.repair_texts').hide();
    $('.repair_text_' + $(this).data('id')).show();
    calc_the_calc();

  })

  $('.calc_input').change(function () {
    calc_the_calc();
  })


  calc_the_calc();


  function initSuperGal() {
    $('.f_scr_gallagy_wrap').each(function () {
      var el = $(this);
      var container = el.closest('.f_scr_gallagy_wrapper');
      el.owlCarousel({
        lazyLoad: true,
        items: 3,
        mouseDrag: true,
        touchDrag: true,
        margin: 20,
        loop: true,
        autoWidth: true,
        startPosition: 0,
        nav: false,
        navText: ['', ''],
        slideBy: 1,
        responsive: {

          0: {
            items: 1,
            autoWidth: false,
            margin: 0,
          },

          768: {
            items: 3,
            autoWidth: true,
          }
        },
        onTranslated: function () {
          if ($('body').outerWidth() > 767) {
            container.find('.f_scr_gallagy_wrap .owl-item').removeClass('not_v active_v').addClass('not_v');
            container.find('.f_scr_gallagy_wrap .owl-item.active:eq(0)').addClass('active_v');
          }
        },

        onInitialized: function () {
          if ($('body').outerWidth() > 767) {
            container.find('.f_scr_gallagy_wrap .owl-item').removeClass('not_v active_v').addClass('not_v');
            container.find('.f_scr_gallagy_wrap .owl-item.active:eq(0)').addClass('active_v');

            setTimeout(function () {
              var s2_w = container.find('.owl-item').outerWidth();
              var s2_w_mar = 20;
              var s2_offset = ($('body').outerWidth() - (s2_w * 1) + (s2_w_mar * 4)) / 2 - (s2_w_mar * 2) - 0;
              container.find('.f_scr_gallagy_wrap .owl-item').css('transform', 'translate3d(' + s2_offset + 'px, 0px, 0px)');
            }, 300)
          }


        },
        onResize: function () {
          if ($('body').outerWidth() > 767) {
            container.find('.f_scr_gallagy_wrap .owl-item').removeClass('not_v active_v').addClass('not_v');
            container.find('.f_scr_gallagy_wrap .owl-item.active:eq(0)').addClass('active_v');

            setTimeout(function () {
              var s2_w = container.find('.owl-item').outerWidth();
              var s2_w_mar = 20;
              var s2_offset = ($('body').outerWidth() - (s2_w * 1) + (s2_w_mar * 4)) / 2 - (s2_w_mar * 2) - 0;
              container.find('.f_scr_gallagy_wrap .owl-item').css('transform', 'translate3d(' + s2_offset + 'px, 0px, 0px)');
            }, 300)
          }
        }
      });

      container.parent().find('.f_scr_gallagy_wrap_right').click(function () {
        el.trigger('next.owl.carousel');
      });
      container.parent().find('.owl-item').click(function (e) {
        e.preventDefault();
        el.trigger('next.owl.carousel');
      });

      container.parent().find('.f_scr_gallagy_wrap_left').click(function () {
        el.trigger('prev.owl.carousel');
      });


      // $(document).on('click', '.f_scr_item', function(){
      //     n = $(this).parent().index();
      //     console.log(n);
      //     el.trigger('to.owl.carousel', n);
      // });


    });

  }

  initSuperGal();

  $(window).resize(function () {
    initSuperGal()

  });


  //Price list

  if ($('.pl_stages_list_item').length) {

    $('.pl_table_body_wrapper').on('jsp-scroll-y.price_table_block', function (e, y) {
      var offset = parseInt($(this).data('offset')) || 0;

      $('.price_table_block').each(function () {
        var $block = $(this);
        if ($block.position().top - offset - 5 <= y) {
          $('.pl_stages_list_item.active').removeClass('active');
          $('.pl_stages_list_item[data-table="' + $block.data('id') + '"]').addClass('active');
        }
      });

    });

    $(window).on('resize.price-tables', function () {
      $('.article_block_table .pl_table_header').each(function () {
        var $wrapper = $(this.parentNode).find('.pl_table_body_wrapper'),
          offset = this.clientHeight - 1;

        $wrapper.data('offset', offset).find('.pl_table_body').css('margin-top', offset);
      });
    }).trigger('resize.price-tables');

    $('.pl_stages_list_item').click(function (e, notscroll) {
      var th_item = $(this).attr('data-table');

      // $('.pl_tables_item').hide();
      // $('.pl_tables_item[data-table='+th_item+']').show();

      // var destination = $('.pl_t_title[data-title='+th_item+']').offset().top;
      // jQuery("html:not(:animated),body:not(:animated)").animate({scrollTop: destination - $('.l-main-block').outerHeight() - 20}, 800);


      // var th_image = $(this).attr('data-img'),
      //     $replacing_image = $('.pl_stages_list_back_image img');

      // if ($replacing_image.attr('src') != th_image) {
      //     $replacing_image.fadeOut(1, function(){
      //         $replacing_image.attr('src', th_image).fadeIn(1);
      //     });
      // }


      if (notscroll !== true) {
        var $scroller = $(this).closest('.price_list_wrap').find('.pl_table_body_wrapper'),
          offset = parseInt($scroller.data('offset')) || 0;

        if ($scroller.data('jsp')) {
          $scroller.data('jsp').scrollToY($('.price_table_block[data-id="' + th_item + '"]').position().top - offset, true);
        } else {
          $scroller.animate({
            scrollTop: $scroller.scrollTop() + $('.price_table_block[data-id="' + th_item + '"]').position().top - offset
          });
        }

      }

      // if( $(window).outerWidth() > 767 ){
      //     if( $('.price_list_right').outerHeight() > $(window).outerHeight() ){

      //         console.log(
      //             $('.l-main-block').outerHeight()
      //         );


      //         $('.price_list_left').height( $('.price_list_right').outerHeight());

      //         $(".pl_stages_wrap").stick_in_parent({
      //             // offset_top: $('.l-main-block').outerHeight()
      //             offset_top: 60 // minifed height of scroll
      //         });

      //         $(".pl_table_header").stick_in_parent({
      //             // offset_top: $('.l-main-block').outerHeight()
      //             offset_top: 60 // minifed height of scroll
      //         });
      //     } else {
      //         $('.price_list_left').css({'height':'initial'});
      //         $(".pl_stages_wrap").trigger("sticky_kit:detach");
      //         $(".pl_table_header").trigger("sticky_kit:detach");

      //     }
      // }

      return false;

    });

  }


  /*$('.pl_stages_list_item').mouseenter(function(){
      var th_image = $(this).attr('data-img');


      $('.pl_stages_list_back_image img').hide(1,function(){
          $(this).attr('src', th_image).show(1);

      });

  }).mouseleave(function(){

      var th_image =  $('.pl_stages_list_item.active').attr('data-img');


      $('.pl_stages_list_back_image img').hide(1,function(){
          $(this).attr('src', th_image).show(1);

      });

  });*/

  //$('.price_list_left').height( $('.price_list_right').outerHeight());

  // $(".pl_stages_wrap").stick_in_parent({
  //     offset_top: $('.l-main-block').outerHeight()
  // });

  // $(".pl_table_header").stick_in_parent({
  //     offset_top: $('.l-main-block').outerHeight()
  // });


  //Start Screen 1 gallary
  $('.ss1_left_gallary').owlCarousel({
    lazyLoad: true,
    loop: true,
    items: 1,
    thumbs: false,
    thumbImage: false,
    dots: true,
    nav: true,
    navText: ['', ''],
    responsive: {
      0: { nav: true },
      768: { nav: true }
    }
  });


  //Start Screen 2 gallary
  $('.ss2_left_gallary').owlCarousel({
    lazyLoad: true,
    loop: true,
    items: 1,
    thumbs: false,
    thumbImage: false,
    dots: true,
    nav: true,
    navText: ['', ''],
    responsive: {
      0: { nav: true },
      768: { nav: true }
    }
  });


  //Start Screen 2 gallary
  $('.ss3_left_gallary').owlCarousel({
    lazyLoad: true,
    loop: true,
    items: 1,
    thumbs: false,
    thumbImage: false,
    dots: true,
    nav: true,
    navText: ['', ''],
    responsive: {
      0: { nav: true },
      768: { nav: true }
    }
  });


  $('.pl_stages_list').each(function () {
    $(this).find('.pl_stages_list_item').eq(0).trigger('click', [true]);
  });


  $('.pps_').click(function (e) {
    var show_delay = 0;
    e.preventDefault();

    if ($('.pp.gallary_pp').hasClass('show')) {
      console.log('add')
      show_delay = 300;
    }
    $('.pp').removeClass('show');

    var th_pp = $(this).attr('data-pp');

    setTimeout(function () {
      $('.pp[data-pp=' + th_pp + ']').addClass('show');
      // disableBodyScroll();
      //disableScroll();
    }, show_delay)

  });

  $(window).on('scroll', function () {
    $('.l-main-block').toggleClass('header_t', window.pageYOffset >= 100);
  });

});

function supergals_init() {
  $('.pp_supergal').each(function () {
    var gal_h = $(this).find('.pp_supergal_item:eq(0)').outerHeight();
    var gal_pp_parent = $('.pp_supergal').parents('.gallary_pp');

    var gal_thumbs = $('.pp_supergal').parents('.gallary_pp_wrap').find('.th_list_wrap');
    var gal_menu = $('.pp_supergal').parents('.gallary_pp_wrap').find('.pp_menu');
    var gal_infoblock = $('.pp_supergal').parents('.gallary_pp_wrap').find('.pp_info_block');

    gal_pp_parent.find('.gallary_pp_wrapper').outerHeight(gal_h);

    if (gal_thumbs.outerHeight() > gal_h) {
      gal_thumbs.outerHeight(gal_h);
      gal_thumbs.jScrollPane({
        showArrows: false
      });

    }

    setTimeout(function () {
      if (gal_menu.outerHeight() > gal_h - gal_infoblock.outerHeight()) {
        gal_menu.outerHeight(gal_h - gal_infoblock.outerHeight() - 23);
        gal_menu.jScrollPane({
          showArrows: false,

        });
      }

    }, 300);

    setTimeout(function () {
      if ($(window).outerWidth() > 474) {
        gal_pp_parent.find('.gallary_pp_block').hide();
        gal_pp_parent.find('.gallary_pp_block:eq(0)').show();
        gal_pp_parent.find('.pp_menu_item:eq(0)').addClass('active');
      } else {
        gal_pp_parent.find('.gallary_pp_block:eq(0)').show();
        gal_pp_parent.find('.pp_menu_item:eq(0)').addClass('active');

        gal_pp_parent.find('.gallary_pp_block:eq(1)').show();
        gal_pp_parent.find('.pp_menu_item:eq(1)').addClass('active');

        gal_pp_parent.find('.gallary_pp_block:eq(2)').show();
        gal_pp_parent.find('.pp_menu_item:eq(2)').addClass('active');

      }
      //console.log('dududu');
      // gal_pp_parent.find('.gallary_pp_block').hide();
      // gal_pp_parent.find('.gallary_pp_block:eq(0)').show();

      // gal_pp_parent.find('.pp_menu_item:eq(0)').addClass('active');
      // gal_pp_parent.find('.gallary_pp_block:eq(1)').show();
      // gal_pp_parent.find('.pp_menu_item:eq(1)').addClass('active');
      // gal_pp_parent.find('.gallary_pp_block:eq(0)').show();
      // gal_pp_parent.find('.pp_menu_item:eq(0)').addClass('active');

    }, 500);
  });
}

function disableScroll() {
  if (window.addEventListener) // older FF
    window.addEventListener('DOMMouseScroll', preventDefault, false);
  window.onwheel = preventDefault; // modern standard
  window.onmousewheel = document.onmousewheel = preventDefault; // older browsers, IE
  window.ontouchmove = preventDefault; // mobile
  document.onkeydown = preventDefaultForScrollKeys;
}

//$(".forms1").insertAfter('<a href="index.html#" class="btn btn_big pp_" data-pp="request">Отправить заявку</a>');

$(".forms1").after('<br /><center><a href="/remont_kvartir_price.html" class="btn"  style="width:100%;">Перейти в раздел</a></center>');
$(".forms2").after('<br /><center><a href="/otdelka_etap.html" class="btn" style="width:100%;">Перейти в раздел</a></center>');
$(".forms3").after('<br /><center><a href="/inzhenernye-sistemy.html" class="btn" style="width:100%;">Перейти в раздел</a></center>');
$(".forms4").after('<br /><center><a href="/sostav_dizajn_proekta.html" class="btn" style="width:100%;">Перейти в раздел</a></center>');

$(".forms01").after('<br /><a href="#" class="btn knopka" style="width:100%;"><span>Заказать</span></a>');